apps/usuario/urls.py
from django.urls import path

from apps.usuario import views

app_name = 'usuario'
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout")
 ]

apps/vianda/urls.py
from django.urls import path
from .views import solicitud_vianda_create

app_name = 'vianda'
urlpatterns = [
    # vianda views
    # path('', vianda_lista, name='vianda_lista'),
    path('create/', solicitud_vianda_create, name='solicitud_vianda_create'),
]

proyecto_parcial2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from apps.usuario.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('usuario', include('apps.usuario.urls', namespace='usuario')),
    path('vianda/', include('apps.vianda.urls', namespace='vianda')),
]

apps/usuario/models.py
from django.db import models

# Create your models here.

apps/vianda/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models


# Create your models here.
class TipoPlato(models.Model):
    descripcion = models.CharField(max_length=200)
    es_activo = models.BooleanField(default=False)

    def __str__(self):
        return self.descripcion


class SolicitudVianda(models.Model):
    SEMANAL = 'Semanal'
    QUINCENAL = 'Quincenal'
    FRECUENCIA_CHOICES = [
        (SEMANAL, 'Semanal'),
        (QUINCENAL, 'Quincenal'),
    ]
    FRECUENCIA_CHOICES = [
        (SEMANAL, 'Semanal'),
        (QUINCENAL, 'Quincenal'),
    ]

    NORMAL = 'Normal'
    DIABETICO = 'Diabetico'
    VEGETARIANO = 'Vegetariano'
    TIPO_MENU_CHOICES = [
        (NORMAL, 'Normal'),
        (DIABETICO, 'Diabetico'),
        (VEGETARIANO, 'Vegetariano'),
    ]

    PENDIENTE = 'Pendiente'
    CONFIRMADO = 'Confirmado'
    CANCELADO = 'Cancelado'
    ESTADOS = [
        (PENDIENTE, 'Pendiente'),
        (CONFIRMADO, 'Confirmado'),
        (CANCELADO, 'Cancelado'),
    ]

    frecuencia = models.CharField(
        max_length=9,
        choices=FRECUENCIA_CHOICES,
        default=SEMANAL,
    )
    tipo_menu = models.CharField(
        max_length=11,
        choices=TIPO_MENU_CHOICES,
        default=SEMANAL,
    )
    fecha_inicio_vianda = models.DateField(verbose_name='Fecha Inicio de Vianda')
    cantidad_vianda = models.IntegerField(validators=[MinValueValidator(1)], default=1)
    estado = models.CharField(
        max_length=10,
        choices=ESTADOS,
        default=PENDIENTE,
    )
    item_tipo_plato = models.ManyToManyField(TipoPlato)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='viandas')

    def __str__(self):
        return f"{self.frecuencia} Tipo Menu {self.tipo_menu }"

apps/vianda/forms.py
from datetime import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.forms import DateInput

from vianda.models import SolicitudVianda


class SolicitudViandaForm(forms.ModelForm):
    class Meta:
        model = SolicitudVianda
        fields = ('frecuencia', 'tipo_menu', 'fecha_inicio_vianda', 'cantidad_vianda', 'estado','item_tipo_plato',
                  'usuario')

    # def clean(self):
    #     cleaned_data = super().clean()
    #     fecha_inicio_vianda = self.cleaned_data['fecha_inicio_vianda']
    #     fecha_actual = date.now()
    #
    #     # Verifica que la fecha de inicio sea mayor a la fecha actual.
    #     if fecha_inicio_vianda < fecha_actual:
    #         raise ValidationError(
    #             {'fecha_inicio_vianda': 'La Fecha de Inicio no puede ser anterior a la fecha de hoy'},
    #             code='invalido'
    #         )
    #     return cleaned_data

apps/usuario/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from django.contrib.auth import authenticate, login, logout


@login_required(login_url='usuario:login')
def index(request):
    return render(request, "base/index.html")


def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect("index")
        else:
            return render(request, "usuario/login.html", {"msj": "Credenciales incorrectas"})
    return render(request, "usuario/login.html")


def logout_view(request):
    logout(request)
    return render(request, "usuario/login.html", {"msj": "Deslogueado"})

apps/vianda/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

# Create your views here.
from vianda.forms import SolicitudViandaForm


def solicitud_vianda_create(request):
    nueva_solicitud_vianda = None
    if request.method == 'POST':
        solicitud_vianda_form = SolicitudViandaForm(request.POST, request.FILES)
        if solicitud_vianda_form.is_valid():
            # Se guardan los datos que provienen del formulario en la B.D.
            nueva_solicitud_vianda = solicitud_vianda_form.save(commit=True)
            messages.success(request,
                             'Se ha agregado correctamente Una Solicitud de Vianda {}'.format(nueva_solicitud_vianda))
            return redirect(reverse('vianda:vianda_detalle', args={nueva_solicitud_vianda.id}))
    else:
        solicitud_vianda_form = SolicitudViandaForm()

    return render(request, 'vianda/vianda_form.html',
                  {'form': solicitud_vianda_form})

apps/usuario/templates/usuario/login.html
{% extends "base/base.html" %}
{% block titulo %}Inicio Sesión{% endblock %}
{% block contenido %}
    <h1>Login de Usuario</h1>
    <hr>
    {% if msj %}
        <div>{{ msj }}</div>
    {% endif %}
    <form action="{% url 'usuario:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value="Login">
    </form>
{% endblock %}

apps/vianda/templates/vianda/vianda_form.html
{% extends "base/base.html" %}
{% block titulo %}Creación de Vianda{% endblock %}
{% block contenido %}
    <h1>Creación de Vianda</h1>
    <form method="post" >
        {% for field in form %}
          <div class="campo">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
          </div><br>
        {% endfor %}
      {% csrf_token %}
      <input type="submit" value="Guardar">
    </form>
{% endblock %}

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block titulo %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'css/estilos.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="contenedor">
            <header>
                <h2>Desarrollo de WebApp - Segundo Parcial de Programación 3</h2>
            </header>
            <nav class="menu">
                <ul>
                  <li class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}"><a href="/">Index</a></li>
                   {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="javascript:void(0)" class="dropbtn">XXX</a>
                        <div class="dropdown-content">
                          <a href="">Listar</a>
                          <a href="{% url 'vianda:solicitud_vianda_create' %}">Crear</a>
                        </div>
                    </li>
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}
                    <span class="usuario">{{ user.username }}&nbsp;&nbsp;<a href="{% url 'usuario:logout' %}">Cerrar Sesión</a>
                    </span>
                {% endif %}
            </nav>
            <section>
                {% block contenido %}
                {% endblock %}
            </section>
            <br>
            <footer>
                <p><strong>@Programación 3 - Ingenieria en Informatica - FTyCAps</strong></p>
            </footer>
        </div>
    </body>
</html>

templates/base/index.html
{% extends "base/base.html" %}
{% block titulo %}Pagina Principal{% endblock %}
{% block contenido %}
    <h1>Portada Principal</h1>

    <p>
        Completar aqui con alguna descripcion del sistema
    </p>
{% endblock %}